<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyVersion>1.0.9691.690</AssemblyVersion>
    <FileVersion>1.0.9691.690</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Extend0\Extend0.csproj" />
  </ItemGroup>

</Project>
