using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

namespace Extend0.MetadataEntry.Generator;

/// <summary>
/// Generates strongly typed MetaDB table wrappers from opt-in <c>*.typed.tablespec.json</c> additional files.
/// </summary>
[Generator]
public sealed class TableSpecTypedApiGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Registers the incremental pipeline that turns typed TableSpec additional files into generated wrappers.
    /// </summary>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var specs = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".typed.tablespec.json", StringComparison.OrdinalIgnoreCase))
            .Select(static (file, cancellationToken) => TypedTableSpecParser.Parse(file, cancellationToken))
            .Where(static spec => spec is not null)
            .Select(static (spec, _) => spec!)
            .Collect();

        context.RegisterSourceOutput(specs, static (productionContext, parsedSpecs) =>
        {
            foreach (var spec in parsedSpecs)
            {
                productionContext.AddSource(
                    $"{spec.WrapperName}.g.cs",
                    SourceText.From(TypedTableSpecEmitter.Emit(spec), Encoding.UTF8));
            }
        });
    }
}

internal sealed class TypedTableSpec
{
    public string Name { get; set; } = "Table";
    public string Namespace { get; set; } = "Extend0.Metadata.Typed.Generated";
    public string WrapperName { get; set; } = "TypedTable";
    public int SchemaVersion { get; set; } = 1;
    public string? SchemaId { get; set; }
    public string? SchemaDescription { get; set; }
    public ImmutableArray<TypedColumnSpec> Columns { get; set; }
}

internal sealed class TypedColumnSpec
{
    public int Index { get; set; }
    public string Name { get; set; } = "Column";
    public string PropertyName { get; set; } = "Column";
    public string ConstantName { get; set; } = "ColumnIndex";
    public int KeyBytes { get; set; }
    public int ValueBytes { get; set; }
    public uint InitialCapacity { get; set; } = 1;
    public bool ReadOnly { get; set; }
    public TypedColumnKind Kind { get; set; }
    public string? ValueType { get; set; }
}

internal enum TypedColumnKind
{
    Raw,
    Value,
    Utf8,
    Refs,
}

internal static class TypedTableSpecEmitter
{
    public static string Emit(TypedTableSpec spec)
    {
        var columnConstants = new StringBuilder();
        var columnProperties = new StringBuilder();
        var constructorAssignments = new StringBuilder();
        var specColumns = new StringBuilder();
        var validationCalls = new StringBuilder();

        foreach (var column in spec.Columns)
        {
            columnConstants.AppendLine($"    public const uint {column.ConstantName} = {column.Index}u;");
            columnProperties.AppendLine($"    public {GetColumnType(column)} {column.PropertyName} {{ get; }}");
            constructorAssignments.AppendLine(
                $"        {column.PropertyName} = new {GetColumnType(column)}(Inner, {column.ConstantName}, {Literal(column.Name)}, {column.KeyBytes}, {column.ValueBytes});");
            specColumns.AppendLine(
                $"            new(global::Extend0.Metadata.Schema.TableSpec.Helpers.PackColumnSize({column.KeyBytes}, {column.ValueBytes}), {Literal(column.Name)}, {BoolLiteral(column.ReadOnly)}, {column.InitialCapacity.ToString(CultureInfo.InvariantCulture)}u),");
            validationCalls.AppendLine(
                $"        ValidateColumn(spec, {column.ConstantName}, {Literal(column.Name)}, {column.KeyBytes}, {column.ValueBytes});");
        }

        var schemaIdInitializer = spec.SchemaId is null
            ? string.Empty
            : $"\n            SchemaId = {Literal(spec.SchemaId)},";
        var schemaDescriptionInitializer = spec.SchemaDescription is null
            ? string.Empty
            : $"\n            SchemaDescription = {Literal(spec.SchemaDescription)},";

        return $$"""
// <auto-generated by Extend0.MetadataEntry.Generator.TableSpecTypedApiGenerator />
#nullable enable

namespace {{spec.Namespace}};

/// <summary>
/// Strongly typed MetaDB wrapper for the {{XmlEscape(spec.Name)}} table.
/// </summary>
public sealed partial class {{spec.WrapperName}}
{
    public const string TableName = {{Literal(spec.Name)}};
    public const int ColumnCount = {{spec.Columns.Length.ToString(CultureInfo.InvariantCulture)}};
    public const int SchemaVersion = {{spec.SchemaVersion.ToString(CultureInfo.InvariantCulture)}};
{{columnConstants.ToString().TrimEnd()}}

    public global::Extend0.Metadata.Contract.IMetadataTable Inner { get; }

{{columnProperties.ToString().TrimEnd()}}

    public {{spec.WrapperName}}(global::Extend0.Metadata.Contract.IMetadataTable table)
    {
        Inner = table ?? throw new global::System.ArgumentNullException(nameof(table));
        ValidateSpec(table.Spec);
{{constructorAssignments.ToString().TrimEnd()}}
    }

    public static {{spec.WrapperName}} Wrap(global::Extend0.Metadata.Contract.IMetadataTable table) => new(table);

    public static global::Extend0.Metadata.Schema.TableSpec CreateSpec(string mapPath) =>
        new(
            TableName,
            mapPath,
            new global::Extend0.Metadata.Schema.ColumnConfiguration[]
            {
{{specColumns.ToString().TrimEnd()}}
            })
        {
            SchemaVersion = SchemaVersion,{{schemaIdInitializer}}{{schemaDescriptionInitializer}}
        };

    public static global::System.Guid Register(
        global::Extend0.Metadata.Contract.IMetaDBManagerCommon manager,
        string mapPath,
        bool createNow = false)
    {
        if (manager is null)
            throw new global::System.ArgumentNullException(nameof(manager));

        return manager.RegisterTable(CreateSpec(mapPath), createNow);
    }

    public static {{spec.WrapperName}} RegisterAndCreate(
        global::Extend0.Metadata.Contract.IMetaDBManager manager,
        string mapPath)
    {
        if (manager is null)
            throw new global::System.ArgumentNullException(nameof(manager));

        var tableId = Register(manager, mapPath, createNow: true);
        return new {{spec.WrapperName}}(manager.GetOrCreate(tableId));
    }

    public static void ValidateSpec(global::Extend0.Metadata.Schema.TableSpec spec)
    {
        if (!string.Equals(spec.Name, TableName, global::System.StringComparison.Ordinal))
            throw new global::System.ArgumentException($"Expected table '{TableName}', got '{spec.Name}'.", nameof(spec));
        if (spec.Columns is null || spec.Columns.Length != ColumnCount)
            throw new global::System.ArgumentException($"Expected {ColumnCount} columns in table '{TableName}'.", nameof(spec));
        if (spec.EffectiveSchemaVersion != SchemaVersion)
            throw new global::System.ArgumentException($"Expected schema version {SchemaVersion}, got {spec.EffectiveSchemaVersion}.", nameof(spec));

{{validationCalls.ToString().TrimEnd()}}
    }

    private static void ValidateColumn(
        global::Extend0.Metadata.Schema.TableSpec spec,
        uint index,
        string name,
        int keyBytes,
        int valueBytes)
    {
        var column = spec.Columns[(int)index];
        var size = global::Extend0.Metadata.CodeGen.MetadataEntrySizeExtensions.Decompose(column.Size);

        if (!string.Equals(column.Name, name, global::System.StringComparison.Ordinal))
            throw new global::System.ArgumentException($"Column {index} expected name '{name}', got '{column.Name}'.", nameof(spec));
        if (size.KeySize != keyBytes || size.ValueSize != valueBytes)
            throw new global::System.ArgumentException($"Column {index} expected size {keyBytes}x{valueBytes}, got {size.KeySize}x{size.ValueSize}.", nameof(spec));
    }
}
""";
    }

    private static string GetColumnType(TypedColumnSpec column) =>
        column.Kind switch
        {
            TypedColumnKind.Value => $"global::Extend0.Metadata.Typed.MetadataValueColumn<{NormalizeValueType(column.ValueType!)}>",
            TypedColumnKind.Utf8 => "global::Extend0.Metadata.Typed.MetadataUtf8Column",
            TypedColumnKind.Refs => "global::Extend0.Metadata.Typed.MetadataRefsColumn",
            _ => "global::Extend0.Metadata.Typed.MetadataRawColumn",
        };

    private static string NormalizeValueType(string typeName)
    {
        var trimmed = typeName.Trim();
        return trimmed switch
        {
            "bool" or "Boolean" or "System.Boolean" => "bool",
            "byte" or "Byte" or "System.Byte" => "byte",
            "sbyte" or "SByte" or "System.SByte" => "sbyte",
            "short" or "Int16" or "System.Int16" => "short",
            "ushort" or "UInt16" or "System.UInt16" => "ushort",
            "int" or "Int32" or "System.Int32" => "int",
            "uint" or "UInt32" or "System.UInt32" => "uint",
            "long" or "Int64" or "System.Int64" => "long",
            "ulong" or "UInt64" or "System.UInt64" => "ulong",
            "float" or "Single" or "System.Single" => "float",
            "double" or "Double" or "System.Double" => "double",
            "decimal" or "Decimal" or "System.Decimal" => "decimal",
            "char" or "Char" or "System.Char" => "char",
            "Guid" or "System.Guid" => "global::System.Guid",
            _ when trimmed.StartsWith("global::", StringComparison.Ordinal) => trimmed,
            _ when trimmed.Contains(".") => "global::" + trimmed,
            _ => trimmed,
        };
    }

    private static string Literal(string value) =>
        "@\"" + value.Replace("\"", "\"\"") + "\"";

    private static string BoolLiteral(bool value) => value ? "true" : "false";

    private static string XmlEscape(string value) =>
        value.Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");
}

internal static class TypedTableSpecParser
{
    private const string StringPropertyRegexTemplate = "\"{0}\"\\s*:\\s*\"((?:\\\\.|[^\"\\\\])*)\"";
    private const string IntegerPropertyRegexTemplate = "\"{0}\"\\s*:\\s*(-?\\d+)";
    private const string BooleanPropertyRegexTemplate = "\"{0}\"\\s*:\\s*(true|false)";

    public static TypedTableSpec? Parse(AdditionalText file, CancellationToken cancellationToken)
    {
        var text = file.GetText(cancellationToken)?.ToString();
        if (string.IsNullOrWhiteSpace(text))
            return null;

        var json = text!;
        var tableName = ReadString(json, "name");
        if (string.IsNullOrWhiteSpace(tableName))
            return null;

        var array = ExtractArray(json, "columns");
        if (array is null)
            return null;

        var namespaceName = SanitizeNamespace(
            ReadString(json, "typedApiNamespace")
            ?? ReadString(json, "apiNamespace")
            ?? "Extend0.Metadata.Typed.Generated");
        var wrapperName = SanitizeIdentifier(
            ReadString(json, "typedApiName")
            ?? ReadString(json, "wrapperName")
            ?? ToPascalCase(tableName!) + "Table",
            "TypedTable");

        var columns = new List<TypedColumnSpec>();
        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var columnJson in ExtractObjects(array))
        {
            var column = ParseColumn(columnJson, columns.Count, usedNames);
            if (column is not null)
                columns.Add(column);
        }

        if (columns.Count == 0)
            return null;

        return new TypedTableSpec
        {
            Name = tableName!,
            Namespace = namespaceName,
            WrapperName = wrapperName,
            SchemaVersion = Math.Max(1, ReadInt(json, "schemaVersion") ?? 1),
            SchemaId = ReadString(json, "schemaId"),
            SchemaDescription = ReadString(json, "schemaDescription"),
            Columns = columns.ToImmutableArray(),
        };
    }

    private static TypedColumnSpec? ParseColumn(string json, int index, HashSet<string> usedNames)
    {
        var name = ReadString(json, "name");
        if (string.IsNullOrWhiteSpace(name))
            return null;

        var kindText = ReadString(json, "kind") ?? string.Empty;
        var valueType = ReadString(json, "valueType") ?? ReadString(json, "type");
        var kind = Classify(kindText, valueType);

        var packed = ReadPackedSize(json, "size");
        var keyBytes = ReadInt(json, "keyBytes") ?? packed?.KeyBytes ?? 0;
        var valueBytes = ReadInt(json, "valueBytes") ?? packed?.ValueBytes ?? GuessValueBytes(kind, valueType, ReadInt(json, "refsPerCell"));
        if (keyBytes < 0 || valueBytes <= 0)
            return null;

        var requestedPropertyName = ReadString(json, "propertyName");
        var propertyName = MakeUniqueIdentifier(
            SanitizeIdentifier(requestedPropertyName ?? ToPascalCase(name!), "Column"),
            usedNames);

        return new TypedColumnSpec
        {
            Index = index,
            Name = name!,
            PropertyName = propertyName,
            ConstantName = propertyName + "Column",
            KeyBytes = keyBytes,
            ValueBytes = valueBytes,
            InitialCapacity = ReadUInt(json, "initialCapacity") ?? ReadUInt(json, "capacity") ?? 1u,
            ReadOnly = ReadBool(json, "readOnly") ?? false,
            Kind = kind,
            ValueType = kind == TypedColumnKind.Value ? valueType! : null,
        };
    }

    private static TypedColumnKind Classify(string kindText, string? valueType)
    {
        if (kindText.Equals("refs", StringComparison.OrdinalIgnoreCase)
            || kindText.Equals("reference-vector", StringComparison.OrdinalIgnoreCase)
            || valueType?.Equals("refs", StringComparison.OrdinalIgnoreCase) == true)
            return TypedColumnKind.Refs;

        if (kindText.Equals("utf8", StringComparison.OrdinalIgnoreCase)
            || kindText.Equals("string", StringComparison.OrdinalIgnoreCase)
            || valueType?.Equals("string", StringComparison.OrdinalIgnoreCase) == true
            || valueType?.Equals("System.String", StringComparison.OrdinalIgnoreCase) == true
            || valueType?.Equals("utf8", StringComparison.OrdinalIgnoreCase) == true)
            return TypedColumnKind.Utf8;

        return string.IsNullOrWhiteSpace(valueType)
            ? TypedColumnKind.Raw
            : TypedColumnKind.Value;
    }

    private static int GuessValueBytes(TypedColumnKind kind, string? valueType, int? refsPerCell) =>
        kind switch
        {
            TypedColumnKind.Refs => 0x80 * Math.Max(1, refsPerCell ?? 1),
            TypedColumnKind.Value => GuessValueTypeBytes(valueType),
            _ => 0,
        };

    private static int GuessValueTypeBytes(string? valueType) =>
        valueType?.Trim() switch
        {
            "bool" or "Boolean" or "System.Boolean" => 1,
            "byte" or "Byte" or "System.Byte" => 1,
            "sbyte" or "SByte" or "System.SByte" => 1,
            "short" or "Int16" or "System.Int16" => 2,
            "ushort" or "UInt16" or "System.UInt16" => 2,
            "int" or "Int32" or "System.Int32" => 4,
            "uint" or "UInt32" or "System.UInt32" => 4,
            "long" or "Int64" or "System.Int64" => 8,
            "ulong" or "UInt64" or "System.UInt64" => 8,
            "float" or "Single" or "System.Single" => 4,
            "double" or "Double" or "System.Double" => 8,
            "decimal" or "Decimal" or "System.Decimal" => 16,
            "char" or "Char" or "System.Char" => 2,
            "Guid" or "System.Guid" => 16,
            _ => 0,
        };

    private static (int KeyBytes, int ValueBytes)? ReadPackedSize(string json, string propertyName)
    {
        var numeric = ReadInt(json, propertyName);
        if (numeric.HasValue)
            return (((numeric.Value >> 16) & 0xFFFF), numeric.Value & 0xFFFF);

        var text = ReadString(json, propertyName);
        if (string.IsNullOrWhiteSpace(text))
            return null;

        var match = Regex.Match(text, @"(\d+)x(\d+)", RegexOptions.IgnoreCase);
        if (!match.Success)
            return null;

        return (
            int.Parse(match.Groups[1].Value, CultureInfo.InvariantCulture),
            int.Parse(match.Groups[2].Value, CultureInfo.InvariantCulture));
    }

    private static string? ExtractArray(string json, string propertyName)
    {
        var match = Regex.Match(json, $"\"{Regex.Escape(propertyName)}\"\\s*:", RegexOptions.IgnoreCase);
        if (!match.Success)
            return null;

        var start = json.IndexOf('[', match.Index + match.Length);
        if (start < 0)
            return null;

        var end = FindBalancedEnd(json, start, '[', ']');
        return end < 0 ? null : json.Substring(start + 1, end - start - 1);
    }

    private static IEnumerable<string> ExtractObjects(string json)
    {
        var index = 0;
        while (index < json.Length)
        {
            var start = json.IndexOf('{', index);
            if (start < 0)
                yield break;

            var end = FindBalancedEnd(json, start, '{', '}');
            if (end < 0)
                yield break;

            yield return json.Substring(start, end - start + 1);
            index = end + 1;
        }
    }

    private static int FindBalancedEnd(string text, int start, char open, char close)
    {
        var depth = 0;
        var inString = false;
        var escaping = false;

        for (var i = start; i < text.Length; i++)
        {
            var ch = text[i];
            if (inString)
            {
                if (escaping)
                {
                    escaping = false;
                    continue;
                }

                if (ch == '\\')
                {
                    escaping = true;
                    continue;
                }

                if (ch == '"')
                    inString = false;

                continue;
            }

            if (ch == '"')
            {
                inString = true;
                continue;
            }

            if (ch == open)
                depth++;
            else if (ch == close)
            {
                depth--;
                if (depth == 0)
                    return i;
            }
        }

        return -1;
    }

    private static string? ReadString(string json, string propertyName)
    {
        var regex = new Regex(string.Format(CultureInfo.InvariantCulture, StringPropertyRegexTemplate, Regex.Escape(propertyName)));
        var match = regex.Match(json);
        return match.Success ? UnescapeJsonString(match.Groups[1].Value) : null;
    }

    private static int? ReadInt(string json, string propertyName)
    {
        var regex = new Regex(string.Format(CultureInfo.InvariantCulture, IntegerPropertyRegexTemplate, Regex.Escape(propertyName)));
        var match = regex.Match(json);
        return match.Success && int.TryParse(match.Groups[1].Value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var value)
            ? value
            : null;
    }

    private static uint? ReadUInt(string json, string propertyName)
    {
        var value = ReadInt(json, propertyName);
        return value.HasValue && value.Value >= 0 ? (uint)value.Value : null;
    }

    private static bool? ReadBool(string json, string propertyName)
    {
        var regex = new Regex(string.Format(CultureInfo.InvariantCulture, BooleanPropertyRegexTemplate, Regex.Escape(propertyName)), RegexOptions.IgnoreCase);
        var match = regex.Match(json);
        return match.Success && bool.TryParse(match.Groups[1].Value, out var value) ? value : null;
    }

    private static string UnescapeJsonString(string value)
    {
        var builder = new StringBuilder(value.Length);
        for (var i = 0; i < value.Length; i++)
        {
            var ch = value[i];
            if (ch != '\\' || i == value.Length - 1)
            {
                builder.Append(ch);
                continue;
            }

            var escaped = value[++i];
            switch (escaped)
            {
                case '"':
                case '\\':
                case '/':
                    builder.Append(escaped);
                    break;
                case 'b':
                    builder.Append('\b');
                    break;
                case 'f':
                    builder.Append('\f');
                    break;
                case 'n':
                    builder.Append('\n');
                    break;
                case 'r':
                    builder.Append('\r');
                    break;
                case 't':
                    builder.Append('\t');
                    break;
                case 'u' when i + 4 < value.Length:
                    var hex = value.Substring(i + 1, 4);
                    if (ushort.TryParse(hex, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out var code))
                    {
                        builder.Append((char)code);
                        i += 4;
                    }
                    break;
            }
        }

        return builder.ToString();
    }

    private static string SanitizeNamespace(string namespaceName)
    {
        var parts = namespaceName.Split(new[] { '.' }, StringSplitOptions.RemoveEmptyEntries)
            .Select(static part => SanitizeIdentifier(part, "Generated"));
        return string.Join(".", parts);
    }

    private static string MakeUniqueIdentifier(string identifier, HashSet<string> usedNames)
    {
        if (usedNames.Add(identifier))
            return identifier;

        var suffix = 2;
        while (!usedNames.Add(identifier + suffix.ToString(CultureInfo.InvariantCulture)))
            suffix++;

        return identifier + suffix.ToString(CultureInfo.InvariantCulture);
    }

    private static string ToPascalCase(string value)
    {
        var builder = new StringBuilder(value.Length);
        var uppercaseNext = true;
        foreach (var ch in value)
        {
            if (!char.IsLetterOrDigit(ch))
            {
                uppercaseNext = true;
                continue;
            }

            builder.Append(uppercaseNext ? char.ToUpperInvariant(ch) : ch);
            uppercaseNext = false;
        }

        return builder.Length == 0 ? "Column" : builder.ToString();
    }

    private static string SanitizeIdentifier(string identifier, string fallback)
    {
        if (string.IsNullOrWhiteSpace(identifier))
            identifier = fallback;

        var builder = new StringBuilder(identifier.Length + 1);
        foreach (var ch in identifier)
            builder.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');

        if (builder.Length == 0)
            builder.Append(fallback);
        if (!char.IsLetter(builder[0]) && builder[0] != '_')
            builder.Insert(0, '_');

        var sanitized = builder.ToString();
        return IsKeyword(sanitized) ? sanitized + "Column" : sanitized;
    }

    private static bool IsKeyword(string identifier)
    {
        switch (identifier)
        {
            case "abstract":
            case "as":
            case "base":
            case "bool":
            case "break":
            case "byte":
            case "case":
            case "catch":
            case "char":
            case "checked":
            case "class":
            case "const":
            case "continue":
            case "decimal":
            case "default":
            case "delegate":
            case "do":
            case "double":
            case "else":
            case "enum":
            case "event":
            case "explicit":
            case "extern":
            case "false":
            case "finally":
            case "fixed":
            case "float":
            case "for":
            case "foreach":
            case "goto":
            case "if":
            case "implicit":
            case "in":
            case "int":
            case "interface":
            case "internal":
            case "is":
            case "lock":
            case "long":
            case "namespace":
            case "new":
            case "null":
            case "object":
            case "operator":
            case "out":
            case "override":
            case "params":
            case "private":
            case "protected":
            case "public":
            case "readonly":
            case "ref":
            case "return":
            case "sbyte":
            case "sealed":
            case "short":
            case "sizeof":
            case "stackalloc":
            case "static":
            case "string":
            case "struct":
            case "switch":
            case "this":
            case "throw":
            case "true":
            case "try":
            case "typeof":
            case "uint":
            case "ulong":
            case "unchecked":
            case "unsafe":
            case "ushort":
            case "using":
            case "virtual":
            case "void":
            case "volatile":
            case "while":
                return true;
            default:
                return false;
        }
    }
}
