<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyVersion>1.1.9691.41434</AssemblyVersion>
    <FileVersion>1.1.9691.41434</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.msbuild" Version="6.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Extend0.Cli\Extend0.Cli.csproj" />
    <ProjectReference Include="..\Extend0.MetadataEntry.Generator\Extend0.MetadataEntry.Generator.csproj" PrivateAssets="all" />
    <ProjectReference Include="..\Extend0.Testing\Extend0.Testing.csproj" />
    <ProjectReference Include="..\Extend0.TestProcessHost\Extend0.TestProcessHost.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <Target Name="CopyTestProcessHost" AfterTargets="Build">
    <ItemGroup>
      <_TestProcessHostFiles Include="$(MSBuildProjectDirectory)\..\Extend0.TestProcessHost\bin\$(Configuration)\net10.0\*" />
    </ItemGroup>
    <Copy SourceFiles="@(_TestProcessHostFiles)" DestinationFolder="$(OutDir)process-host" SkipUnchangedFiles="true" />
  </Target>

</Project>
